### ISSUE TITLE
[1.16.4] NBT issue

### ISSUE THREAD

**Issue by Daejangnamu** [blay09/FarmingForBlockheads#108]
![444](https://user-images.githubusercontent.com/52635462/99995179-5cb0d280-2dfd-11eb-9890-1bcd34eaf42b.png)
I wanted to add this item to the market.

![1](https://user-images.githubusercontent.com/52635462/99994140-faa39d80-2dfb-11eb-9619-383629a2fa39.png)

Adding Tint nbt causes client crash.
Is it wrong?

[crash-2020-11-24_02.52.20-client.txt](https://github.com/blay09/FarmingForBlockheads/files/5584825/crash-2020-11-24_02.52.20-client.txt)

**Comment by BlayTheNinth** [comment]
It looks like you might have to put `[0.66, 6.66, 6.66]` instead of `["0.66f", "6.66f", "6.66f"]`.

**Comment by Daejangnamu** [comment]
> It looks like you might have to put `[0.66, 6.66, 6.66]` instead of `["0.66f", "6.66f", "6.66f"]`.

[0.66, 6.66, 6.66] same client crash T_T

**Comment by Daejangnamu** [comment]
![141414](https://user-images.githubusercontent.com/52635462/100025387-00b17280-2e2c-11eb-8953-1ba41c134e35.png)

If "1" belongs to "Tint" group, it crashes.

**Comment by BlayTheNinth** [comment]
It looks like Minecraft invented its own JSON that supports values like `6.66f` which would have to be used here, but obviously with them not being standard JSON they will fail to load when used in a normal JSON context.

I will probably have to add support to supply the NBT as a plain string instead of JSON to cover cases like this.
