### ISSUE TITLE
Market not summoning merchant from the sky.

### ISSUE THREAD

**Issue by ghost** [blay09/FarmingForBlockheads#121]
**Versions**
- Minecraft Version: 1.16.5
- Forge Version: 36.1.24
- Mod Version: 9.3.2

https://user-images.githubusercontent.com/42738314/120778953-4368ab80-c52f-11eb-8495-14eeecc06874.mp4

**Comment by Explode007** [comment]
Have the same issue here.

**Comment by IchHabeHunger54** [comment]
https://github.com/blay09/FarmingForBlockheads/blob/b8a31f1bc55cf83ef7ee4501c3adddb69b33da08/src/main/java/net/blay09/mods/farmingforblockheads/block/MarketBlock.java#L77

The merchant spawns, but does not fall. All your merchants remain 172 blocks above your market, because they don't get a negative y-movement. Check it by teleporting up, if you like.

**Comment by bengrebe** [comment]
Oh yeah, they do spawn all the way up there. But they don't fall until you get somewhat close to them.

**Comment by BlayTheNinth** [comment]
This is likely due to performance mods disabling entity ticking for entities far away.

**Comment by ghost** [comment]
True, this is Perfomant issue. Can be fixed by https://github.com/Sajeyson/Journey-of-Sorcerer/blob/b8a68c623ec8bd0844d5b8219dd49c170703a5c7/minecraft/config/performant-common.toml#L48
