### ISSUE TITLE
[1.18.1] Registry error with quark on latest FFB

### ISSUE THREAD

**Issue by itsdinkd** [blay09/FarmingForBlockheads#139]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

39.0.8

### Mod Version

latest from today

### Describe the Issue

![image](https://user-images.githubusercontent.com/35115304/147713351-1f3b33b5-aa74-416c-a9a4-0ad213d1c6f5.png)

**Comment by BlayTheNinth** [comment]
Cannot reproduce and can't really be since the files containing glowshroom and glowcelium have been deleted. Maybe you have a separate data pack / MarketRegistry.json specifying them or are running an outdated version.

Do not put "latest" as mod version as it does not let me verify that you are actually on the latest version.

**Comment by itsdinkd** [comment]
Apologies. I opened up like 15 tickets yesterday and working on two modpack updates at the same time. 

So I put this in MarketRegistry but only after I was receiving the message in original post, thinking this is how I could disable it, which didn't do anything. Though, I created this in MarketRegistry on the second most recent version, and not on the latest update, 9.0.2

![image](https://user-images.githubusercontent.com/35115304/147777088-d5fea9d5-41fb-41ea-a0df-37b0637a081c.png)
