### ISSUE TITLE
Fertilized Farmland appears to be incompatible with Immersive Engineering Hemp

### ISSUE THREAD

**Issue by MuteTiefling** [blay09/FarmingForBlockheads#191]
### Minecraft Version

1.19.2 (LTS)

### Mod Loader

Forge

### Mod Loader Version

43.2.14

### Mod Version

11.3.1

### Balm Version

4.5.7

### Describe the Issue

It is not possible to plant Industrial Hemp seeds on any fertilized farmland. 

Planting Hemp on Vanilla Farmland, and then adding any form of fertilizer also causes the plant to break and pop off. 

https://github.com/EnigmaticaModpacks/Enigmatica9/issues/486

**Comment by BlayTheNinth** [comment]
It looks like Immersive Engineering specifically only accepts vanilla farmland blocks. This is not something I can fix on my side.

**Comment by MuteTiefling** [comment]
I was able to fix it in the pack by removing your farmland from the dirt tag. Does this have some unexpected consequences?

Refer to the linked issue and relevant commits attached to it.

**Comment by BlayTheNinth** [comment]
Immersive Engineering [specifically only returns `true` for `mayPlaceOn` if the block is `Blocks.FARMLAND`](https://github.com/BluSunrize/ImmersiveEngineering/blob/1.20.1/src/main/java/blusunrize/immersiveengineering/common/blocks/plant/HempBlock.java#L73) which is Vanilla's farmland. If it's working despite that there must be some other magic involved, such as another mod patching it or something.

The dirt tag is required, as otherwise melons and pumpkins will not be able to grow on fertilized farmland.
