### ISSUE TITLE
Bugged farmland from a diffrent mod doesnt allow fertilization while using a certain hoe from a diffrent mod

### ISSUE THREAD

**Issue by R3TR0xSN1P3R** [blay09/FarmingForBlockheads#200]
### Minecraft Version

1.20.x

### Mod Loader

Forge

### Mod Loader Version

Forge 47.3.1

### Mod Version

1.20-16.0.1

### Balm Version

1.20.x-1.0

### Describe the Issue

when farming with a regular hoe you get farm land from mine craft which you can fertilize, but when you how with a neptunium hoe from aquaculture 2 you get Farmland from aquaculture 2 it isnt able to be fertilized
![image](https://github.com/TwelveIterationMods/CookingForBlockheads/assets/88951606/aabcd0ff-632f-44ba-8913-8a1d6f19635a)

**Comment by BlayTheNinth** [comment]
Just like how fertilizer replaces the farmland block with a fertilized farmland block, Aquaculture seems to have its own farmland block as well. It's not really something that can be fixed in a reasonable manner that wouldn't require me to also add fertilized blocks and special handling of all other mods that add farmlands.

I could have the fertilizer act on the farmland and "revert" the aquaculture farmland back to a normal vanilla farmland / FFB fertilized farmland, but that would result in whatever features Aquaculture uses its custom farmland block for to not work anymore.
