### ISSUE TITLE
File not going where Twitch wants it to go

### ISSUE THREAD

**Issue by Allalous** [blay09/FarmingForBlockheads#74]
Hello,

I'm trying to make a modpack with this mod in it (cuz it's an awesome mod( and every time I try to get it published, Twitch tells me:

" The following files belong to CurseForge-hosted projects, and should therefore not be added directly to zip files:
overrides/mods/FarmingForBlockheads_1.12.2-3.1.28.jar
overrides/mods/reauth-3.6.0.jar

These files should, instead, be referenced in the manifest.json file generated by the Twitch Desktop App during a profile export. "

I've looked into the export file and for some reason, those mods aren't going into the right spot and I'm not sure how to fix this.

![image](https://user-images.githubusercontent.com/9722546/72531714-ade45300-3837-11ea-88f3-218beef9550a.png)

**Comment by BlayTheNinth** [comment]
Try contacting [CurseForge or TwitchApp support](https://twitchpartnerships.force.com/curseforge/s/), there isn't anything I can do because I just upload the mod files to CurseForge normally. You could also try just deleting the FarmingForBlockheads jar from the export and adding Farming for Blockheads to the manifest.json manually, or removing and re-adding the mod to the pack before exporting again.

**Comment by Allalous** [comment]
I've sent the twitch support ppl a ticket two days ago and still waiting to hear back from them, that's why I came here to see if I could get something. How do you add stuff to the manifest? I don't want to break anything lol

**Comment by BlayTheNinth** [comment]
I don't know, look at what's in there already and make it match that. I have never used Twitch's export feature so I don't even know what the manifest looks like.

**Comment by Allalous** [comment]
alright, I try that and see what happens
