### ISSUE TITLE
[1.16.1] Crash on world join

### ISSUE THREAD

**Issue by NielsPilgaard** [blay09/FarmingForBlockheads#98]
A player reported crashing on world join on my Discord, it seems to be related to Fertilized Farmland.
Log with crash at the bottom: https://paste.ee/p/HC0LB

### Versions
- FarmingForBlockheads_1.16.1-7.0.0
- Forge 1.16.1-32.0.66

**Comment by steelfoot** [comment]
I'm adding to this one, as the crash seems to be identical: https://paste.ee/p/OASJa  I'm using an identical version of Farming for Blockheads and Forge as well. I am, however, on single player instead of a multi-player server.

The crash is definitely related to fertilized farmland, and occurs at a random interval after a crop is planted on the fertilized farmland (presumably when some check or update is done, maybe crop growth itself?). It affects all types of fertilized farmland as well, both dry and hydrated, with an identical crash log. I will note that Niller's crash log mentions a pumpkin stem; my crash was caused by wheat, and testing shows carrots also crash, so I'm assuming it's probably crop-agnostic.
